language: python
python:
  - "3.6"
before_install:
  - chmod +x tests/tests.sh
install: "pip install -r requirements.txt coverage coveralls"
env:
  - FLASK_ENV=Testing
script:
  - mv tests/run_server.py .
  - tests/scripts/tests.sh
after_success:
  - coverage combine
  - coveralls
